// test
export const SET_TEXT = 'SET_TEXT';

// auth
export const SET_AUTH_STATUS = 'SET_AUTH_STATUS';
export const SET_COGNITO_USER = 'SET_COGNITO_USER';
export const SET_DB_USER = 'SET_DB_USER';
export const SIGN_OUT = 'SIGN_OUT';

// meetups
export const FETCH_MEETUPS = 'FETCH_MEETUPS';
export const FETCH_USER_MEETUPS = 'FETCH_USER_MEETUPS';

// posts
export const FETCH_GENERAL_POSTS = 'FETCH_GENERAL_POSTS';
export const FETCH_QUESTION_POSTS = 'FETCH_QUESTION_POSTS';
export const FETCH_TIP_POSTS = 'FETCH_TIP_POSTS';
export const FETCH_TRADE_POSTS = 'FETCH_TRADE_POSTS';
export const FETCH_USER_GENERAL_POSTS = 'FETCH_USER_GENERAL_POSTS';
export const FETCH_USER_QUESTION_POSTS = 'FETCH_USER_QUESTION_POSTS';
export const FETCH_USER_TIP_POSTS = 'FETCH_USER_TIP_POSTS';
export const FETCH_USER_TRADE_POSTS = 'FETCH_USER_TRADE_POSTS';

// others
export const FETCH_NEWS = 'FETCH_NEWS';
export const SET_CURRENT_LOCATION = 'SET_CURRENT_LOCATION';

// gallery
export const FETCH_GALLERY = 'FETCH_GALLERY';
export const FETCH_USER_GALLERY = 'FETCH_USER_GALLERY';

// history
export const FETCH_FIRENDS_RECENT_ACTIVITY = 'FETCH_FIRENDS_RECENT_ACTIVITY';
